registers:
  drive_address: "0000:48:00.0"
  register_trials: 5
  settings:
    -
      address: 338
      new_value: d020f
    -
      address: 338
      new_value: d021f
    -
      address: 338
      new_value: d200f
    -
      address: 338
      new_value: 8020f
    -
      address: 338
      new_value: 4020f

