registers:
  drive_address: "0000:48:00.0"
  register_trials: 28
  settings:
    -
      address: 271
      new_value: "0002"
    -
      address: 271
      new_value: "0004"
    -
      address: 271
      new_value: "0008"
    -
      address: 271
      new_value: "0010"
    -
      address: 271
      new_value: "0020"
    -
      address: 271
      new_value: "0040"
    -
      address: 271
      new_value: "0080"
    -
      address: 271
      new_value: "0100"
    -
      address: 271
      new_value: "0004"
    -
      address: 271
      new_value: "2004"
    -
      address: 271
      new_value: "4004"
    -
      address: 271
      new_value: "8004"
    -
      address: 271
      new_value: "10004"
    -
      address: 271
      new_value: "20004"
    -
      address: 271
      new_value: "40004"
    -
      address: 271
      new_value: "80004"
    -
      address: 271
      new_value: "100004"
    -
      address: 272
      new_value: "ffff0001"
    -
      address: 272
      new_value: "ffff0002"
    -
      address: 272
      new_value: "ffff0004"
    -
      address: 272
      new_value: "ffff0008"
    -
      address: 272
      new_value: "ffff00010"
    -
      address: 272
      new_value: "ffff0020"
    -
      address: 272
      new_value: "ffff0000"
    -
      address: 272
      new_value: "8fff0000"
    -
      address: 272
      new_value: "0fff0000"
    -
      address: 272
      new_value: "08ff0000"
    -
      address: 272
      new_value: "00ff0000"
