benchmark:
    warm_up_time: 30
    run_time: 7200
    stats_binary:
        name: "pt-diskstats"
        named_args:
            iterations: 7200
            devices-regex: "fioa1"
        unamed_args: ""
        extra_args: " > diskstats.log"

mysqld_buffer_sizes: [24G]
trials: 1
