benchmark:
    warm_up_time: 30
    run_time: 1800
    stats_binary:
        name: "pt-diskstats"
        named_args:
            iterations: 1805
            devices-regex: "rssdb"
        unamed_args: ""
        extra_args: " > diskstats.log"

mysqld_buffer_sizes: [24G]
trials: 1
