vsphere:
    host: "10.102.206.20"
    username: "moussab"
    password: "vmware1!"
    datacenter: "DevelopmentDatacenter"

vms:
   "PD_Guest_1_136":
    RAM: 8
   "PD_Guest_2_137":
    RAM: 8
   "PD_Guest_4_139":
    RAM: 8
   "PD_Guest_5_140":
    RAM: 8
#vms: ["PD_Guest_1_136", "PD_Guest_2_137", "PD_Guest_3_138"]
