binary: "sudo fio"

name: "fio"

global:
    thread: 
    numjobs: 1
    iodepth: 1
    group_reporting:
    bs: 16k
    norandommap: 1
    refill_buffers:
    direct: 1
    ioengine: "sync"
    runtime: 600
    time_based:

jobs:
    rand-write-16k:
        rw: randwrite
        stonewall:
sweeps:
    global:
        numjobs: [1, 2, 4, 8, 16, 32, 64, 128, 256]    

