binary: "sudo fio"

name: "fio"

global:
    thread: 
    numjobs: 8
    iodepth: 32
    group_reporting:
    bs: 4k
    norandommap: 1
    refill_buffers:
    direct: 1
    ioengine: "libaio"
    runtime: 43200
    time_based:
    write_bw_log:
    write_iops_log:
    write_lat_log:

jobs:
    rand-write-4k:
        rw: randwrite
