binary: "sudo fio"

name: "fio"

global:
    direct: 1
    thread: 
    group_reporting:
    time_based:
    norandommap: 1
    refill_buffers:
    runtime: 90
    ioengine: "libaio"
    write_bw_log:
    write_iops_log:
    write_lat_log:
    log_avg_msec: 30000
	
jobs:
    rand-read-128k:
        rw: randread
        bs: 128k
        numjobs: 8
        iodepth: 1

    rand-write-128k:
        rw: randwrite
        bs: 128k
        numjobs: 8
        iodepth: 1

    seq-read-128k:
        rw: read
        bs: 128k
        numjobs: 1
        iodepth: 256

    seq-write-128k:
        rw: write
        bs: 128k
        numjobs: 1
        iodepth: 256

    rand-read-4k:
        rw: randread
        bs: 4k
        numjobs: 8
        iodepth: 32

    rand-write-4k:
        rw: randwrite
        bs: 4k
        numjobs: 8
        iodepth: 32

    seq-read-4k:
        rw: read
        bs: 4k
        numjobs: 1
        iodepth: 256

    seq-write-4k:
        rw: write
        bs: 4k
        numjobs: 1
        iodepth: 256

    rand-read-16k:
        rw: randread
        bs: 16k
        numjobs: 8
        iodepth: 8

    rand-write-16k:
        rw: randwrite
        bs: 16k
        numjobs: 8
        iodepth: 8

    seq-read-16k:
        rw: read
        bs: 16k
        numjobs: 1
        iodepth: 256

    seq-write-16k:
        rw: write
        bs: 16k
        numjobs: 1

partition:
  id: 83
  size: 100000
  format:
    extra_args: " -f -d su=16384,sw=16 "
    label: "100Gtest"
        
