binary: "fio"

name: "fio"

global:
    thread: 
    numjobs: 1
    iodepth: 1
    cpus_allowed: "1,2,3,4,5,6,7,8,9,10,11,12"
    size: 100g
    group_reporting:
    bs: 16k
    norandommap: 1
    randrepeat: 0
    direct: 1
    ioengine: "libaio"
    runtime: 300
    time_based:

jobs:
    rw_64_36:
        rw: randrw
        rwmixread: 36
        rwmixwrite: 64
        stonewall:

sweeps:
    global:
        numjobs: [1]
        iodepth: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]
