mysql:
    m1:
      binary: "/usr/sbin/mysqld"
      named_args:
          user: "root"
          datadir: "./test_tmp/data1"
          innodb_buffer_pool_size: 24G
          innodb_data_home_dir: "./test_tmp/data1"
          innodb_log_group_home_dir: "./test_tmp/data1"
          innodb_data_file_path: "ibdata1:100M:autoextend"
          innodb_file_per_table: 1
          innodb_flush_log_at_trx_commit: 1
          innodb_log_files_in_group: 2
          innodb_log_file_size: "8G"
          innodb_thread_concurrency: 0
          innodb_fast_checksum: 1
          innodb_flush_method : "O_DIRECT"
          innodb_write_io_threads: 1
          innodb_read_io_threads: 1
          innodb_io_capacity: 200
          innodb_log_buffer_size: 256M
          #innodb_max_dirty_pages_pct: 90
          innodb_flush_neighbor_pages: "none"
          innodb_adaptive_flushing_method: "keep_average"
          innodb_buffer_pool_restore_at_startup: 300
          max_connections: 2000
          max_prepared_stmt_count: 500000
          max_connect_errors: 10
          query_cache_size: 0
          query_cache_type: 0
          table_cache: 2048
          max_allowed_packet: 16M
          binlog_cache_size: 16M
          max_heap_table_size: 64M
          tmp_table_size: 64M
          sort_buffer_size: 4M
          join_buffer_size: 4M
          thread_cache_size: 1000
          ft_min_word_len: 4
          thread_stack: 192K
          back_log: 50
          skip-grant-tables:
          skip-name-resolve:
      extra_args: ""
    m2:
      binary: "/usr/sbin/mysqld"
      named_args:
          user: "root"
          datadir: "./test_tmp/data2"
          innodb_buffer_pool_size: 24G
          innodb_data_home_dir: "./test_tmp/data2"
          innodb_log_group_home_dir: "./test_tmp/data2"
          innodb_data_file_path: "ibdata1:100M:autoextend"
          innodb_file_per_table: 1
          innodb_flush_log_at_trx_commit: 1
          innodb_log_files_in_group: 2
          innodb_log_file_size: "8G"
          innodb_thread_concurrency: 0
          innodb_fast_checksum: 1
          innodb_flush_method : "O_DIRECT"
          innodb_write_io_threads: 1
          innodb_read_io_threads: 1
          innodb_io_capacity: 200
          innodb_log_buffer_size: 256M
          #innodb_max_dirty_pages_pct: 90
          innodb_flush_neighbor_pages: "none"
          innodb_adaptive_flushing_method: "keep_average"
          innodb_buffer_pool_restore_at_startup: 300
          max_connections: 2000
          max_prepared_stmt_count: 500000
          max_connect_errors: 10
          query_cache_size: 0
          query_cache_type: 0
          table_cache: 2048
          max_allowed_packet: 16M
          binlog_cache_size: 16M
          max_heap_table_size: 64M
          tmp_table_size: 64M
          sort_buffer_size: 4M
          join_buffer_size: 4M
          thread_cache_size: 1000
          ft_min_word_len: 4
          thread_stack: 192K
          back_log: 50
          skip-grant-tables:
          skip-name-resolve:
      extra_args: ""
