solution:
    name: "flashcache"
    named_args:
        target_devices: "/dev/sdd1"
        SSD_devices: "/dev/rssda"
        cache_mode: "thru"
        cache_size: 64g
        mount_point: "./test_tmp/data"
        flashcache_mod: "modules/CentOS5.7-2.6.18/flashcache.ko"
