solution:
    name: "velobit"
    named_args:
        mount_point: "./test_tmp/data"
        SSD_devices: "/dev/rssda"
        ram_sizes: [2G, 3G, 4G, 5G, 6G, 7G, 8G, 9G, 10G]
        reserved_memory: "4G"
        write_cache_depth: 0
        sequential_IO_filtering: "n"
