solution:
    name: "velobit"
    named_args:
        mount_point: "./test_tmp/data"
        SSD_devices: "/dev/rssda"
        write_cache_depths: ["0", "50", "100", "150"]
        reserved_memory: "4G"
        write_cache_depth: 0
        sequential_IO_filtering: "n"
