mysql:
    dbname: "tpcc2500"

#Usage: tpcc_start -h server_host -P port -d database_name -u mysql_user -p mysql_password 
# -w warehouses -c connections -r warmup_time -l running_time -i report_interval -f report_file

benchmark:
    name: "tpcc"
    binary: "./bin/tpcc-mysql/tpcc_start"
    src: "./bin/tpcc-mysql/src"
    short_args:
        h: "localhost"
        d: "tpcc2500"
        u: "root"
        p: "\"\""
        w: 2500
        c: 16
        r: 30
        l: 600
        i: 10
    extra_args: ""
    warm_up_time: 90
    run_time: 300

drives:
    source_data:
        data:
            src: "/backup_data/mysql/tpcc/2500/data.tar.gz"
            dst: "./test_tmp/data"
        log:
            src: "/backup_data/mysql/tpcc/2500/log.tar.gz"
            dst: "./test_tmp/log"
